### ISSUE TITLE
Regression in v0.5.11

### ISSUE THREAD

**Issue by ijlee2** [ember-tooling/ember-eslint-parser#135]
## Background

When an Ember project consumes [a shared `eslint` configuration](https://github.com/ijlee2/frontend-configs/blob/2.2.1/packages/eslint/ember/README.md), then running `lint:js` in that project results in many error messages:

<details>

<summary>Partial log from <code>lint:js</code></summary>

```sh
[ember-eslint-parser] Failed to parse tsconfig: tsconfig.json Error: error TS5012: Cannot read file 'tsconfig.json': ENOENT: no such file or directory, open '/node_modules/@ijlee2-frontend-configs/eslint-config-ember/v1-app/tsconfig.json'.
  at Object.onUnRecoverableConfigFileDiagnostic (/node_modules/.pnpm/@typescript-eslint+tsconfig-utils@8.42.0_typescript@5.9.2/node_modules/@typescript-eslint/tsconfig-utils/dist/getParsedConfigFile.js:55:19)
  at Object.getParsedCommandLineOfConfigFile (/node_modules/.pnpm/typescript@5.9.2/node_modules/typescript/lib/typescript.js:42456:10)
  at Object.getParsedConfigFile (/node_modules/.pnpm/@typescript-eslint+tsconfig-utils@8.42.0_typescript@5.9.2/node_modules/@typescript-eslint/tsconfig-utils/dist/getParsedConfigFile.js:51:29)
  at parseAllowJsFromTsconfig (/node_modules/.pnpm/ember-eslint-parser@0.5.11_@babel+core@7.28.3_@typescript-eslint+parser@8.42.0_eslint@9_010b21943b1257599f6ee846cf94aa41/node_modules/ember-eslint-parser/src/parser/gjs-gts-parser.js:31:34)
  at getAllowJs (/node_modules/.pnpm/ember-eslint-parser@0.5.11_@babel+core@7.28.3_@typescript-eslint+parser@8.42.0_eslint@9_010b21943b1257599f6ee846cf94aa41/node_modules/ember-eslint-parser/src/parser/gjs-gts-parser.js:112:12)
  at Object.parseForESLint (/node_modules/.pnpm/ember-eslint-parser@0.5.11_@babel+core@7.28.3_@typescript-eslint+parser@8.42.0_eslint@9_010b21943b1257599f6ee846cf94aa41/node_modules/ember-eslint-parser/src/parser/gjs-gts-parser.js:142:58)
  at Object.parse (/node_modules/.pnpm/eslint@9.34.0_jiti@1.21.7/node_modules/eslint/lib/languages/js/index.js:270:15)
  at ParserService.parseSync (/node_modules/.pnpm/eslint@9.34.0_jiti@1.21.7/node_modules/eslint/lib/services/parser-service.js:34:27)
  at #flatVerifyWithoutProcessors (/node_modules/.pnpm/eslint@9.34.0_jiti@1.21.7/node_modules/eslint/lib/linter/linter.js:1846:38)
  at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/node_modules/.pnpm/eslint@9.34.0_jiti@1.21.7/node_modules/eslint/lib/linter/linter.js:2189:43)
  at /node_modules/.pnpm/eslint@9.34.0_jiti@1.21.7/node_modules/eslint/lib/linter/linter.js:1773:17
  at Array.map (<anonymous>)
  at Linter._verifyWithFlatConfigArrayAndProcessor (/node_modules/.pnpm/eslint@9.34.0_jiti@1.21.7/node_modules/eslint/lib/linter/linter.js:1768:30)
  at Linter._verifyWithFlatConfigArray (/node_modules/.pnpm/eslint@9.34.0_jiti@1.21.7/node_modules/eslint/lib/linter/linter.js:2275:16)
  at Linter.verify (/node_modules/.pnpm/eslint@9.34.0_jiti@1.21.7/node_modules/eslint/lib/linter/linter.js:1677:10)
  at Linter.verifyAndFix (/node_modules/.pnpm/eslint@9.34.0_jiti@1.21.7/node_modules/eslint/lib/linter/linter.js:2557:20)
  at verifyText (/node_modules/.pnpm/eslint@9.34.0_jiti@1.21.7/node_modules/eslint/lib/eslint/eslint-helpers.js:1179:45)
  at readAndVerifyFile (/node_modules/.pnpm/eslint@9.34.0_jiti@1.21.7/node_modules/eslint/lib/eslint/eslint-helpers.js:1320:10)
```

</details>

I traced the bug to #131, because the errors go away when I pin `ember-eslint-parser` to `0.5.10`.

## Reproduction

https://github.com/ijlee2/ember-workshop/tree/bug-ember-eslint-parser

```sh
# Switch to the bug-ember-eslint-parser branch
git checkout git@github.com:ijlee2/ember-workshop.git
cd ember-workshop
git checkout bug-ember-eslint-parser
pnpm install

# Check 0.5.10 (no error messages should appear)
cd my-app
pnpm lint:js

# Check 0.5.11 (error messages should appear)
git revert da79b5e627e41003cb61fcbb1faac2c7abc27895
pnpm i
rm .eslintcache
pnpm lint:js
```

**Comment by wagenet** [comment]
@ijlee2 Do you have a tsconfig.json?

**Comment by patricklx** [comment]
Something is trying to load node_modules/@ijlee2-frontend-configs/eslint-config-ember/v1-app/tsconfig.json

But that doesn't exist:
https://www.npmjs.com/package/@ijlee2-frontend-configs/eslint-config-ember?activeTab=code

**Comment by patricklx** [comment]
This is the reason: https://github.com/ijlee2/frontend-configs/blob/306813cca9d9eab2a4b5b7db9130ee0d4f3046bf/packages/eslint/ember/v1-app/index.mjs#L37

@ijlee2

**Comment by ijlee2** [comment]
@wagenet Yes, the consuming app has a `tsconfig.json`. In the reproduction example, you can see it at https://github.com/ijlee2/ember-workshop/blob/bug-ember-eslint-parser/my-app/tsconfig.json. (The real problem occurs in a production app(s), where we can see hundreds or more of these error messages being logged, which seemed to slow down linting in CI.)

As @patricklx noted, the code introduced in #131 tries to find a `tsconfig.json` at a path that doesn't exist in `node_modules`. I'm not exactly sure what feature/issue #131 wanted to solve, but would guess that the `tsconfig.json` ideally refers to the consuming app's file, which lives next to its `eslint.config.mjs`/`.eslintrc.js`.

**Comment by ijlee2** [comment]
In https://github.com/ijlee2/ember-workshop/commit/34ce7b6088a83cc7226292aa606c4dd08349e26c, I patched `@ijlee2-frontend-configs/eslint-config-ember` to have `tsconfigRootDir: dirname(fileURLToPath(import.meta.url))`. The errors still occurred, however.

```sh
[ember-eslint-parser] Failed to parse tsconfig: tsconfig.json Error: error TS5012: Cannot read file 'tsconfig.json': ENOENT: no such file or directory, open '/ember-workshop/node_modules/.pnpm/@ijlee2-frontend-configs+eslint-config-ember@2.1.1_patch_hash=bb231cd2d190ded6bd40891be_516ae6f9bd048df497d5b40c3b357313/node_modules/@ijlee2-frontend-configs/eslint-config-ember/v1-app/tsconfig.json'.
```

**Comment by patricklx** [comment]
in blueprint it works, because that file will be copied to project directory. 
`tsconfigRootDir: import.meta.dirname`, will be resolved to the directory of the current file. so `tsconfigRootDir` will be in node_modules.
there is no good solution here I think. 
* make it use `process.cwd()`, but that will only work for some cases.
* export the config as a function, passing the `import.meta.dirname` from the importing eslint config

**Comment by ijlee2** [comment]
> there is no good solution here I think.

In addition to the options listed above, I wonder if another could be to ask people to enable a flag instead of trying to find where their `tsconfig.json` is and parsing the file.

From https://github.com/ember-tooling/ember-eslint-parser/pull/131#issuecomment-3111419567, it seemed like that was the original approach.
